--전자결재 결재자
SELECT * FROM MEMBER;
SELECT * FROM ER_AP_STORAGE;


--DROP TABLE ER_AP_STORAGE;

CREATE TABLE ER_AP_STORAGE (
	ER_AP_STORAGE_KEY	NUMBER		NOT NULL,
	ER_AP_STORAGE_NAME	VARCHAR2(50)		NOT NULL,
	MEMBER_KEY	NUMBER		NOT NULL,
	ER_AP_KEY	number		NULL,
	ER_AP_TEAM_NAME	VARCHAR2(50)		NULL,
	ER_AP_JOB_NAME	VARCHAR2(50)		NULL,
	ER_AP_NAME	VARCHAR2(50)		NULL,
	ER_AP_CATEGORY	VARCHAR2(50)		NOT NULL,
	ER_AP_ORDERBY	NUMBER		NULL
);

ALTER TABLE ER_AP_STORAGE ADD CONSTRAINT PK_ER_AP_STORAGE PRIMARY KEY (
	ER_AP_STORAGE_KEY
);

INSERT INTO
			er_ap_storage
			(
				ER_AP_STORAGE_KEY,
				ER_AP_STORAGE_NAME,
				MEMBER_KEY,
				ER_AP_KEY,
				ER_AP_TEAM_NAME,
				ER_AP_JOB_NAME,
				ER_AP_NAME,
				ER_AP_CATEGORY,
				ER_AP_ORDERBY
			)
		VALUES(
			SEQ_ER_AP_STORAGE_KEY.nextval,
			'결재라인1',
			5,
			4,
			'개발팀',
			'대표이사',
			'박진형',
			'결재',
			1
		);
SELECT 
			ER_AP_STORAGE_KEY,
			ER_AP_STORAGE_NAME,
			MEMBER_KEY,
			ER_AP_KEY,
			ER_AP_TEAM_NAME,
			ER_AP_JOB_NAME,
			ER_AP_NAME,
			ER_AP_CATEGORY,
			ER_AP_ORDERBY
		FROM
			ER_AP_STORAGE
		WHERE
			MEMBER_KEY = 5;

DROP SEQUENCE SEQ_ER_AP_STORAGE_KEY;

CREATE SEQUENCE SEQ_ER_AP_STORAGE_KEY
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;

SELECT SEQ_ER_APPROVER_KEY.nextval FROM DUAL;