--전체 생성된 테이블 조회
SELECT table_name 
FROM user_tables;

select * from er_form 
LEFT JOIN ER_FORM_FOLDER USING (ER_FORM_FOLDER_key)
	 where ER_FORM_YN = 'Y' and er_form_name like '%신청%'
	 order by er_form_orderby;


SELECT * FROM ER_DOCUMENT ed ;
SELECT * from ER_APPROVAL_LINE ;
SELECT * FROM MEMBER;
SELECT * FROM ER_AL_STORAGE;
SELECT * FROM ER_APPROVAL_LINE eal ;
SELECT * FROM ER_APROVAL_MEMBER eam ;
SELECT * FROM ER_FILE ;
SELECT * FROM ER_STORAGE es ;
SELECT * FROM ER_DOCUMENT ed ;
SELECT * FROM ER_FORM_FOLDER;
SELECT * FROM ER_FORM;

--DROP TABLE ER_FORM CASCADE CONSTRAINTS;
--DROP sequence SEQ_ER_FORM;
--DROP sequence SEQ_ER_FORM_ORDERBY;
--DROP TABLE ER_FORM_FOLDER CASCADE CONSTRAINTS;
--DROP sequence SEQ_ER_FORM_FOLDER;
--DROP sequence SEQ_ER_FORM_FOLDER_ORDERBY;

--생성
CREATE TABLE ER_FORM (
	ER_FORM_KEY	NUMBER	NOT NULL,
	ER_FORM_NAME	VARCHAR2(500)	NOT NULL,
	ER_FORM_CREATER	NUMBER	NOT NULL,
	ER_FORM_CREATE_DATE	DATE	DEFAULT SYSDATE NOT NULL,
	ER_FORM_FOLDER_KEY	NUMBER	NOT NULL,
	ER_FORM_YN	CHAR	DEFAULT 'Y' NOT NULL,
	ER_FORM_UPDATER	NUMBER	NULL,
	ER_FORM_UPDATE_DATE	DATE	DEFAULT SYSDATE NULL,
	ER_FORM_ORDERBY	NUMBER	NULL
);

CREATE TABLE ER_FORM_FOLDER (
	ER_FORM_FOLDER_KEY	NUMBER	NOT NULL,
	ER_FORM_FOLDER_NAME	VARCHAR2(500)	NOT NULL,
	ER_FORM_FOLDER_CREATER	NUMBER	NOT NULL,
	ER_FORM_FOLDER_CREATEDATE DATE DEFAULT sysdate	NOT NULL,
	ER_FORM_FOLDER_UPDATER	NUMBER	NULL,
	ER_FORM_FOLDER_UPDATEDATE	DATE	NULL,
	ER_FORM_FOLDER_ORDERBY	NUMBER	NULL
);

ALTER TABLE ER_FORM ADD CONSTRAINT PK_ER_FORM PRIMARY KEY (
	ER_FORM_KEY
);

ALTER TABLE ER_FORM_FOLDER ADD CONSTRAINT PK_ER_FORM_FOLDER PRIMARY KEY (
	ER_FORM_FOLDER_KEY
);
--ALTER TABLE ER_FORM_FOLDER modify ER_FORM_FOLDER_CREATEDATE DEFAULT SYSDATE ;


--ALTER TABLE ER_FORM ADD er_form_folder_key NUMBER ;

--문서 시퀀스(자바에서 문자열로 추가할 예정)
CREATE SEQUENCE SEQ_ER_FORM
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;
CREATE SEQUENCE SEQ_ER_FORM_FOLDER
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;
CREATE SEQUENCE SEQ_ER_FORM_FOLDER_ORDERBY
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;
CREATE SEQUENCE SEQ_ER_FORM_ORDERBY
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;

--데이터
INSERT INTO ER_FORM values(SEQ_ER_FORM.nextval, '일반문서', 1, default, 1, 'Y', '', '', SEQ_ER_FORM_ORDERBY.NEXTVAL);
INSERT INTO ER_FORM values(SEQ_ER_FORM.nextval, '초과근무 신청서', 1, default, 2, 'Y', '', '', SEQ_ER_FORM_ORDERBY.NEXTVAL);
INSERT INTO ER_FORM values(SEQ_ER_FORM.nextval, '휴가 신청서', 1, default, 2, 'Y', '', '', SEQ_ER_FORM_ORDERBY.NEXTVAL);
SELECT * FROM ER_FORM;

--DELETE FROM er_form_folder WHERE er_form_folder_key = 2;
SELECT * FROM ER_FORM_FOLDER;
INSERT INTO ER_FORM_FOLDER VALUES(SEQ_ER_FORM_FOLDER.NEXTVAL, '기본양식', 1, sysdate, '', '', SEQ_ER_FORM_FOLDER_ORDERBY.NEXTVAL);
INSERT INTO ER_FORM_FOLDER VALUES(SEQ_ER_FORM_FOLDER.NEXTVAL, '근태신청서', 2, sysdate, '', '', SEQ_ER_FORM_FOLDER_ORDERBY.NEXTVAL);