SELECT
		d.ER_DOC_KEY, 
		    d.ER_DOC_SERIAL_KEY, 
		    d.ER_DOC_WRITER, 
		    d.ER_DOC_TITLE, 
		    d.ER_DOC_CREATE_DATE, 
		    d.ER_DOC_EMERGENCY_YN, 
		    d.ER_DOC_DELETE_YN, 
		    d.ER_DOC_STOARGE, 
		    d.ER_DOC_FILENAME,
		    d.ER_DOC_STATE,
		    d.ER_DOC_STATE_UPDATE_DATE, 
		    d.ER_DOC_LAST_UPDATER, 
		    d.ER_DOC_LAST_UPDATE_REASON,
		    a1.ER_APPROVER_KEY,
		    a1.MEMBER_KEY,
		    a1.ER_APPROVER_NAME,
		    a1.ER_APPROVER_TEAM,
		    a1.ER_APPROVER_JOB,
		    a1.ER_APPROVAL_CATEGORY,
		    a1.ER_APPROVAL_STATE,
		    a1.ER_APPROVAL_OPINION, 
		    a1.ER_DOC_SERIAL_KEY,
		    a1.ER_APPROVAL_DATE,
		    a1.ER_APPROVAL_ORDERBY,
		    er.ER_REFERER_KEY,
		    er.ER_DOC_SERIAL_KEY,
		    er.ER_REFERER_TEAM_NAME,
		    er.ER_REFERER_JOB_NAME,
		    er.ER_REFERER_NAME,
		    er.MEMBER_KEY
		FROM 
		    er_document d
		LEFT JOIN 
		    er_aprover a1
		ON 
		    d.ER_DOC_SERIAL_KEY = a1.ER_DOC_SERIAL_KEY
		LEFT JOIN 
			ER_REFERER er 
		ON
			d.ER_DOC_SERIAL_KEY = er.ER_DOC_SERIAL_KEY
		WHERE    
			d.er_doc_state = '처리중' --처리중 문서
		ORDER BY  
			d.er_doc_emergency_yn DESC,
			d.er_doc_create_date;

SELECT    *
			FROM      er_document d
			join er_aprover ea
			USING    (er_doc_serial_key)
			WHERE     d.er_doc_writer = ${no}
			AND       d.er_doc_state = '처리중'
			ORDER BY  d.er_doc_emergency_yn DESC,
			          ea.er_approval_orderby;
		
		
SELECT * FROM ER_DOCUMENT ed ;
SELECT * from ER_APPROVAL_LINE ;
SELECT * from ER_APROVER ;
SELECT * FROM MEMBER;
SELECT * FROM ER_AL_STORAGE;
SELECT * FROM ER_APPROVAL_LINE eal ;
SELECT * FROM ER_APROVER ea ;
SELECT * FROM ER_REFERENCE er ;
SELECT * FROM ER_FILE ;
SELECT * FROM ER_STORAGE es ;
SELECT * FROM DEPARTMENT d ;
SELECT * FROM ER_FORM ef ;
SELECT * FROM ER_FORM_FOLDER eff ;
		
DROP TABLE ER_REFERER;

SELECT * FROM ER_REFERER er ;
CREATE TABLE ER_REFERER (
	ER_REFERER_KEY	NUMBER		NOT NULL,
	ER_DOC_SERIAL_KEY	VARCHAR2(500)		NOT NULL,
	ER_REFERER_TEAM_NAME	VARCHAR2(50)		NULL,
	ER_REFERER_JOB_NAME	VARCHAR(255)		NULL,
	ER_REFERER_NAME	VARCHAR2(50)		NOT NULL,
	MEMBER_KEY NUMBER NOT null
);

ALTER TABLE ER_REFERER ADD CONSTRAINT PK_ER_REFERER PRIMARY KEY (
	ER_REFERER_KEY
);

DROP sequence SEQ_ER_REFERER_KEY;

CREATE SEQUENCE SEQ_ER_REFERER_KEY
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;
COMMIT;
SELECT SEQ_ER_REFERER_KEY.nextval FROM DUAL;