--전체 생성된 테이블 조회
SELECT table_name 
FROM user_tables;

SELECT * FROM ER_DOCUMENT ed ;
SELECT * from ER_APPROVAL_LINE ;
SELECT * FROM MEMBER;
SELECT * FROM ER_AL_STORAGE;
SELECT * FROM ER_APPROVAL_LINE eal ;
SELECT * FROM ER_APROVAL_MEMBER eam ;
SELECT * FROM ER_FILE ;
SELECT * FROM ER_STORAGE es ;
SELECT * FROM ER_DOCUMENT ed ;
SELECT * FROM ER_FORM_FOLDER;
SELECT * FROM ER_FORM;

DROP TABLE ER_FORM CASCADE CONSTRAINTS;
DROP sequence SEQ_ER_FORM;
DROP sequence SEQ_ER_FORM_ORDERBY;
DROP TABLE ER_FORM_FOLDER CASCADE CONSTRAINTS;
DROP sequence SEQ_ER_FORM_FOLDER;
DROP sequence SEQ_ER_FORM_FOLDER_ORDERBY;

--생성
CREATE TABLE ER_FORM_FOLDER (
	ER_FORM_FOLDER_KEY	VARCHAR(255)	NOT NULL,
	ER_FORM_FOLDER_NAME varchar(100) NOT NULL,
	ER_FORM_KEY	varchar(1000)	NOT NULL,
	ER_FORM_FOLDER_ORDERBY	NUMBER	NULL
);

ALTER TABLE ER_FORM_FOLDER ADD CONSTRAINT PK_ER_FORM_FOLDER PRIMARY KEY (
	ER_FORM_FOLDER_KEY
);
ALTER TABLE ER_FORM_FOLDER modify (ER_FORM_KEY varchar(1000));

CREATE TABLE ER_FORM (
	ER_FORM_KEY	NUMBER	NOT NULL,
	ER_FORM_NAME	VARCHAR2(200) NOT NULL,
	ER_FORM_UPDATER	NUMBER	NOT NULL,
	ER_FORM_YN	VARCHAR(50) DEFAULT 'Y' NOT null,
	ER_FORM_ORDERBY	VARCHAR(50)	NULL,
	ER_FORM_UPDATE_DATE	DATE	DEFAULT SYSDATE NOT NULL
);

ALTER TABLE ER_FORM ADD CONSTRAINT PK_ER_FORM PRIMARY KEY (
	ER_FORM_KEY
);

--문서 시퀀스(자바에서 문자열로 추가할 예정)
CREATE SEQUENCE SEQ_ER_FORM
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;
CREATE SEQUENCE SEQ_ER_FORM_FOLDER
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;
CREATE SEQUENCE SEQ_ER_FORM_FOLDER_ORDERBY
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;
CREATE SEQUENCE SEQ_ER_FORM_ORDERBY
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;

--데이터
--양식: 고유번호, 양식명, 최종 수정자, 사용여부, 정렬순서, 최종수정일자
INSERT INTO ER_FORM values(SEQ_ER_FORM.nextval, '일반문서', 1, 'Y', SEQ_ER_FORM_ORDERBY.nextval, default);
INSERT INTO ER_FORM values(SEQ_ER_FORM.nextval, '초과근무 신청서', 1, 'Y', SEQ_ER_FORM_ORDERBY.nextval, default);
INSERT INTO ER_FORM values(SEQ_ER_FORM.nextval, '휴가 신청서', 1, 'Y', SEQ_ER_FORM_ORDERBY.nextval, default);
--양식 폴더: 고유번호, 폴더명, 양식고유번호, 정렬순서
DELETE FROM er_form_folder WHERE er_form_folder_key = 2;

--INSERT INTO ER_FORM_FOLDER VALUES(1, '기본양식', '[1]',1);
--INSERT INTO ER_FORM_FOLDER VALUES(2, '근태신청서', '[2, 3]',2);
INSERT INTO ER_FORM_FOLDER VALUES(SEQ_ER_FORM_FOLDER.NEXTVAL, '기본양식', '[1]',SEQ_ER_FORM_FOLDER_ORDERBY.NEXTVAL);
INSERT INTO ER_FORM_FOLDER VALUES(SEQ_ER_FORM_FOLDER.NEXTVAL, '근태신청서', '[2,3]',SEQ_ER_FORM_FOLDER_ORDERBY.NEXTVAL);
