--전자결재 결재자
SELECT * FROM MEMBER;
SELECT * FROM ER_APROVer eam;

--DROP TABLE ER_APROVER;

CREATE TABLE ER_APROVER (
	ER_APPROVER_KEY		NUMBER		NOT NULL,
	MEMBER_KEY			NUMBER		NOT NULL,
	ER_APPROVER_NAME	VARCHAR2(50)		NOT NULL,
	ER_APPROVER_TEAM	VARCHAR2(50)		NOT NULL,
	ER_APPROVER_JOB		VARCHAR2(50)		NULL,
	ER_APPROVAL_CATEGORY	VARCHAR2(50)	NOT NULL,
	ER_APPROVAL_STATE	VARCHAR2(50)		NOT NULL,
	ER_APPROVAL_OPINION	VARCHAR2(1000)		NULL,
	ER_DOC_KEY			VARCHAR2(50)		NOT NULL,
	ER_APPROVAL_DATE	DATE	DEFAULT sysdate	NULL,
	ER_APPROVAL_ORDERBY	NUMBER		NOT NULL
);

ALTER TABLE ER_APROVER ADD CONSTRAINT PK_ER_APROVER PRIMARY KEY (
	ER_APPROVER_KEY
);

DROP sequence SEQ_ER_APPROVER_KEY;
CREATE SEQUENCE SEQ_ER_APPROVER_KEY
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;

SELECT SEQ_ER_APPROVER_KEY.nextval FROM DUAL;
INSERT INTO ER_aprover values(SEQ_ER_APPROVER_KEY.nextval, 2,'나팀장', '경영팀', '팀장', '검토', '대기', null, '20240606-D1F2-1', null, 1);

INSERT INTO ER_aprover values(SEQ_ER_APPROVER_KEY.nextval, 2, '김팀장', '기술지원팀', '팀장', '검토', '대기', null, AAAtDXAABAAALCRAAD, null, 1);