--전자결재 결재자
SELECT * FROM MEMBER;
SELECT * FROM ER_APROVAL_MEMBER eam;

DROP TABLE ER_APROVAL_MEMBER CASCADE CONSTRAINTS;
--DROP sequence SEQ_ER_FORM_FOLDER;

ALTER TABLE ER_APROVAL_MEMBER
DROP COLUMN er_approval_line_key;
ALTER TABLE ER_APROVAL_MEMBER ADD ER_DOC_KEY VARCHAR2(50) NOT null;
ALTER TABLE ER_APROVAL_MEMBER ADD ER_DOC_KEY VARCHAR2(50) NOT null;
ALTER TABLE ER_APROVAL_MEMBER ADD ER_APPROVAL_ORDERBY number;
ALTER TABLE ER_APROVAL_MEMBER ADD ER_approval_date DATE DEFAULT sysdate;

DROP TABLE ER_APROVER;

CREATE TABLE ER_APROVER (
	ER_APPROVER_KEY		NUMBER		NOT NULL,
	MEMBER_KEY			NUMBER		NOT NULL,
	ER_APPROVER_NAME	VARCHAR2(50)		NOT NULL,
	ER_APPROVER_TEAM	VARCHAR2(50)		NOT NULL,
	ER_APPROVER_JOB		VARCHAR2(50)		NULL,
	ER_APPROVAL_CATEGORY	VARCHAR2(50)	NOT NULL,
	ER_APPROVAL_STATE	VARCHAR2(50)		NOT NULL,
	ER_APPROVAL_OPINION	VARCHAR2(1000)		NULL,
	ER_DOC_KEY			VARCHAR2(50)		NOT NULL,
	ER_APPROVAL_DATE	DATE	DEFAULT sysdate	NOT NULL,
	ER_APPROVAL_ORDERBY	NUMBER		NOT NULL
);


ALTER TABLE ER_APROVER ADD CONSTRAINT PK_ER_APROVER PRIMARY KEY (
	ER_APPROVER_KEY
);

CREATE SEQUENCE SEQ_ER_APPROVER_KEY
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
CACHE 20;