INSERT INTO BOARD (
    BOARD_KEY, 
    BOARD_CATEGORY_KEY, 
    MEMBER_KEY, 
    BOARD_DETAIL, 
    BOARD_ENROLL_DATE, 
    BOARD_UPDATE_DATE, 
    BOARD_DELETE, 
    BOARD_TITLE
) VALUES (
    10, 2, 5, 
    'IT 부서의 새로운 정책이 안내됩니다. 모든 직원들은 확인 후 준수해 주시기 바랍니다.', 
    TO_DATE('2024-07-30 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
    TO_DATE('2024-07-30 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
    'N', '새로운 IT 정책 안내'
);
SELECT BOARD_KEY, COUNT(*)
FROM BOARD
GROUP BY BOARD_KEY
HAVING COUNT(*) > 1;

DELETE FROM BOARD
WHERE BOARD_KEY IN (
    SELECT BOARD_KEY
    FROM (
        SELECT BOARD_KEY, ROW_NUMBER() OVER (PARTITION BY BOARD_KEY ORDER BY BOARD_KEY) AS rnum
        FROM BOARD
    )
    WHERE rnum > 1
);
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'SYS_C0079592';
-- PRIMARY KEY 컬럼 확인
SELECT COLUMN_NAME
FROM USER_CONS_COLUMNS
WHERE CONSTRAINT_NAME = (
    SELECT CONSTRAINT_NAME
    FROM USER_CONSTRAINTS
    WHERE TABLE_NAME = 'BOARD' AND CONSTRAINT_TYPE = 'P'
);
SELECT * FROM BOARD;
SELECT * FROM MEMBER;

INSERT INTO BOARD (
    BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE, BOARD_TITLE
) VALUES (
    121, 2, 121, '신규 공지사항입니다.', SYSDATE, SYSDATE, 'N', '신규 공지사항'
);
-- 게시판만 조회
SELECT * FROM BOARD
WHERE BOARD_CATEGORY_KEY = 1;

-- 공지사항만 조회
SELECT * FROM BOARD
WHERE BOARD_CATEGORY_KEY = 2;




