SELECT * FROM CHATTING_ROOM ;
SELECT * FROM CHATTING_FILE ;
SELECT * FROM CHATTING_MESSAGE cm ;
SELECT * FROM MEMBER;
SELECT *
  FROM all_sequences;
  
 
ALTER TABLE CHATTING_FILE MODIFY(CHAT_MSG_FILE_POST varchar(200)); 


SELECT * FROM MEMBER WHERE MEMBER_ID='1';

ALTER TABLE CHATTING_MESSAGE MODIFY CHAT_MSG_DETAIL VARCHAR2(1000 CHAR);