SELECT * from ER_APROVER  ORDER BY ER_DOC_SERIAL_KEY desc;

SELECT * FROM ER_FILE ORDER BY ER_FILE_UPLOAD_DATE desc;


SELECT * FROM ER_DOCUMENT ed ORDER BY ER_DOC_CREATE_DATE DESC;
SELECT * FROM ER_DOCUMENT ed WHERE ER_DOC_STATE = '처리완료' ORDER BY ER_DOC_CREATE_DATE DESC;



SELECT *
--			d.ER_DOC_KEY,
--			d.ER_DOC_SERIAL_KEY,
--			d.ER_DOC_WRITER,
--			d.ER_DOC_TITLE,
--			d.ER_DOC_CREATE_DATE,
--			d.ER_DOC_EMERGENCY_YN,
--			d.ER_DOC_DELETE_YN,
--			d.ER_DOC_STORAGE_KEY,
--			d.ER_DOC_FILENAME, 
--			d.ER_DOC_STATE, 
--			d.ER_DOC_STATE_UPDATE_DATE,
--			d.ER_DOC_LAST_UPDATER,
--			d.ER_DOC_LAST_UPDATE_REASON,
--			d.ER_DOC_COMPLETE_DATE,
--			d.ER_DOC_FORM_KEY,
--			f.ER_FILE_KEY,
--			f.ER_FILE_ORI_NAME,
--			f.ER_FILE_RENAME,
--			f.ER_DOC_KEY,
--			f.ER_DOC_SERIAL_KEY,
--			f.ER_FILE_SIZE,
--			f.ER_FILE_FORM,
--			f.ER_FILE_UPLOAD_DATE,
--			f.ER_FILE_ORDERBY,
--			f.ER_FILE_UPLODAER,
--			f.ER_FILE_UPDATE_DATE,
--			f.ER_FILE_UPDATER,
--			f.ER_FILE_UPDATE_REASON,
--			ea.ER_APPROVER_KEY,
--			ea.MEMBER_KEY,
--			ea.ER_APPROVER_NAME,
--			ea.ER_APPROVER_TEAM_KEY,
--			d2.DEPARTMENT_NAME,
--			ea.ER_APPROVER_JOB_KEY,
--			j.JOB_NAME,
--			ea.ER_APPROVAL_CATEGORY,
--			ea.ER_APPROVAL_STATE,
--			ea.ER_APPROVAL_OPINION,
--			ea.ER_DOC_SERIAL_KEY,
--			ea.ER_APPROVAL_DATE,
--			ea.ER_APPROVAL_ORDERBY,
--			er.ER_REFERER_KEY,
--			er.ER_DOC_SERIAL_KEY,
--			er.ER_REFERER_TEAM_KEY,
--			d3.DEPARTMENT_NAME as ER_REFERER_TEAM_NAME,
--			er.ER_REFERER_JOB_KEY,
--			j2.JOB_NAME as ER_REFERER_JOB_NAME,
--			er.ER_REFERER_NAME,
--			er.MEMBER_KEY,
--			s.ER_STORAGE_NAME,
--			s.ER_STORAGE_TERM,
--			sf.ER_FOLDER_NAME
		FROM   
			er_document d
        LEFT JOIN 
       		er_aprover ea ON d.ER_DOC_SERIAL_KEY = ea.ER_DOC_SERIAL_KEY
--		LEFT JOIN
--      		ER_REFERER er ON d.ER_DOC_SERIAL_KEY = er.ER_DOC_SERIAL_KEY 
--		LEFT JOIN
--			job j ON ea.ER_APPROVER_JOB_KEY = j.JOB_KEY
--		LEFT JOIN
--			job j2 ON er.ER_REFERER_JOB_KEY = j2.JOB_KEY 
--		LEFT JOIN
--			DEPARTMENT d2 ON ea.ER_APPROVER_TEAM_KEY = d2.DEPARTMENT_KEY 
--		LEFT JOIN
--			DEPARTMENT d3 ON er.ER_REFERER_TEAM_KEY = d3.DEPARTMENT_KEY 
        LEFT JOIN 
        	er_file f ON d.ER_DOC_SERIAL_KEY = f.ER_DOC_SERIAL_KEY 
--        LEFT JOIN
--      		ER_STORAGE s ON d.ER_DOC_STORAGE_KEY = s.ER_STORAGE_KEY
--      	LEFT JOIN
--      		ER_STORAGE_FOLDER sf ON s.ER_STORAGE_FOLDER_KEY = sf.ER_FOLDER_KEY
		WHERE  
			d.ER_DOC_KEY = 383
		ORDER BY
			ea.ER_APPROVAL_ORDERBY asc,
			ER_FILE_ORDERBY;

SELECT * FROM ER_DOCUMENT ed ORDER BY ER_DOC_CREATE_DATE DESC;   
SELECT * FROM ER_DOCUMENT ed WHERE ER_DOC_STATE = '처리완료' ORDER BY ER_DOC_CREATE_DATE DESC; 

