<<<<<<< HEAD
SELECT * FROM CHATTING_IS_READ cir ;


 
SELECT * FROM CHATTING_ROOM cr;

SELECT * FROM CHATTING_GROUP cg ORDER BY chat_room_key ;

SELECT * FROM CHATTING_MESSAGE cm ORDER BY CHAT_MSG_TIME desc ;

SELECT * FROM chatting_IS_READ LEFT JOIN CHATTING_GROUP cg using(member_key);


DELETE FROM chatting_message;
DELETE FROM CHATTING_GROUP;
DELETE FROM CHATTING_ROOM;
DELETE FROM chatting_IS_READ;
=======

SELECT * FROM job;
SELECT * FROM MEMBER;
DELETE FROM MEMBER;
CREATE SEQUENCE SEQ_JOB;
DROP SEQUENCE SEQ_JOB;
DELETE FROM JOB;
>>>>>>> branch 'dev' of https://github.com/JinHyung-dev/NPNC.git
