INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (4, 1, 2, '점심 메뉴 추천해주세요', '오늘 점심 뭐 먹을까요? 추천 부탁드립니다!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (5, 1, 3, '팀 회식 일정 조율', '다음 주 팀 회식 날짜 조율합시다. 다들 가능한 날짜 댓글로 남겨주세요.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (6, 1, 100, '책 추천 받습니다', '최근에 읽은 좋은 책 있으면 추천해주세요.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (7, 1, 1, '사무실 식물 키우기', '사무실에 작은 화분을 놓으려고 합니다. 키우기 쉬운 식물 추천해주세요!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (8, 1, 121, '취미 공유해요', '다들 어떤 취미 생활을 즐기고 계신가요? 공유해봅시다.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (9, 1, 122, '주말 여행지 추천', '이번 주말에 갈 만한 여행지 추천해주세요!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (10, 1, 123, '기타 연습 모임', '기타 연습 같이 하실 분 찾습니다. 관심 있는 분 댓글 달아주세요!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (11, 1, 4, '오늘의 명언', '오늘의 명언: "성공은 작은 노력을 반복하는 데서 옵니다."', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (12, 1, 140, '영화 추천 받습니다', '주말에 볼 만한 영화 추천 부탁드려요!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (13, 1, 5, '운동 같이 하실 분?', '퇴근 후 같이 운동하실 분 찾습니다. 관심 있는 분은 댓글 주세요.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (14, 1, 6, '사무실 내 식물 관리 일정', '사무실 내 식물 관리 일정을 공지합니다. 관심 있는 분 참여 부탁드려요.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (15, 1, 8, '캠핑 장비 추천', '캠핑 장비 추천 부탁드립니다. 좋은 제품 있으면 공유해주세요.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (16, 1, 9, '자전거 출퇴근 도전기', '자전거로 출퇴근 도전해보려 합니다. 팁 있으면 알려주세요!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (17, 1, 160, '사내 독서 모임', '사내 독서 모임에 관심 있으신 분들 모집합니다. 함께 책 읽고 이야기 나눠요.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (18, 1, 185, '업무 스트레스 관리법', '업무 스트레스 어떻게 관리하시나요? 좋은 방법 있으면 공유 부탁드립니다.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (19, 1, 200, '점심시간 운동 추천', '점심시간에 할 수 있는 간단한 운동 추천 부탁드려요.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (20, 1, 201, '사내 요가 모임', '사내 요가 모임을 시작하려 합니다. 관심 있으신 분들 댓글 부탁드려요.', SYSDATE, SYSDATE, 'N');

SELECT * FROM BOARD ORDER BY BOARD_KEY DESC;
