SELECT * FROM AB_EXTERNAL;
INSERT INTO AB_EXTERNAL (AB_EXTERNAL_KEY, MEMBER_KEY, AB_CATEGORY_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_BOOKMARK, AB_COMPANY) VALUES (1, 101, 1, 'John Doe', '010-1234-5678', 'john.doe@example.com', 'Y', 'ABC Corp');
SELECT * FROM AB_CATEGORY;
INSERT INTO AB_CATEGORY (AB_CATEGORY_KEY,AB_CATEGORY_NAME) VALUES (1,'외부주소록');
