-- 데이터 41
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    41, 3, '이민수', '010-1234-5678', 'lee.minsu@company.com',
    'M', 'IT', '프로그래머', '소프트웨어 개발 및 유지보수',
    'N', '테크 솔루션 주식회사', 'N'
);

-- 데이터 42
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    42, 3, '김하늘', '010-2345-6789', 'kim.haneul@company.com',
    'F', '마케팅', '디지털 마케팅 전문가', '온라인 광고 캠페인 관리',
    'Y', '테크 솔루션 주식회사', 'N'
);

-- 데이터 43
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    43, 3, '박정우', '010-3456-7890', 'park.jungwoo@company.com',
    'M', '재무', '재무 담당', '예산 계획 및 자금 조달',
    'N', '테크 솔루션 주식회사', 'N'
);

-- 데이터 44
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    44, 3, '최수영', '010-4567-8901', 'choi.su-young@company.com',
    'F', '기술 지원', '기술 지원 담당', '고객 기술 문제 해결',
    'Y', '테크 솔루션 주식회사', 'N'
);

-- 데이터 45
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    45, 3, '서지민', '010-5678-9012', 'seo.jimin@company.com',
    'F', 'HR', '인사 관리자', '인사 및 직원 복지 관리',
    'N', '테크 솔루션 주식회사', 'N'
);

-- 데이터 46
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    46, 3, '이정훈', '010-6789-0123', 'lee.junghoon@company.com',
    'M', '전략', '전략 기획 전문가', '기업 전략 및 목표 설정',
    'Y', '테크 솔루션 주식회사', 'N'
);

-- 데이터 47
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    47, 3, '김서현', '010-7890-1234', 'kim.seohyun@company.com',
    'F', '디자인', '그래픽 디자이너', '그래픽 디자인 및 브랜딩',
    'N', '테크 솔루션 주식회사', 'N'
);

-- 데이터 48
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    48, 3, '정민우', '010-8901-2345', 'jeong.minwoo@company.com',
    'M', '운영', '운영 매니저', '운영 시스템 및 절차 관리',
    'Y', '테크 솔루션 주식회사', 'N'
);

-- 데이터 49
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    49, 3, '하나래', '010-9012-3456', 'ha.narae@company.com',
    'F', '지원', '고객 지원 관리자', '고객 요청 및 문제 해결',
    'N', '테크 솔루션 주식회사', 'N'
);

-- 데이터 50
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    50, 3, '백승찬', '010-0123-4567', 'baek.seungchan@company.com',
    'M', '기획', '비즈니스 기획자', '사업 기획 및 실행',
    'Y', '테크 솔루션 주식회사', 'N'
);
