SELECT * FROM BOARD;
INSERT INTO BOARD (BOARD_KEY,BOARD_CATEGORY_KEY,MEMBER_KEY,BOARD_DETAIL,BOARD_ENROLL_DATE,BOARD_UPDATE_DATE)
VALUES(1,1,1,'board1',TO_DATE('2023-07-18','YYYY-MM-DD'),TO_DATE('2023-07-18', 'YYYY-MM-DD'));
