
SELECT * FROM CHATTING_IS_READ cir ;
SELECT * FROM CHATTING_GROUP LEFT JOIN MEMBER USING(MEMBER_KEY);

 
SELECT * FROM CHATTING_ROOM cr;

SELECT * FROM CHATTING_GROUP cg ORDER BY chat_room_key ;

SELECT * FROM CHATTING_MESSAGE cm ORDER BY CHAT_MSG_TIME desc ;

SELECT * FROM chatting_IS_READ LEFT JOIN CHATTING_GROUP cg using(member_key);


DELETE FROM chatting_message;
DELETE FROM CHATTING_GROUP;
DELETE FROM CHATTING_ROOM;
DELETE FROM chatting_IS_READ;

SELECT * FROM job;
SELECT * FROM MEMBER;
DELETE FROM MEMBER;
CREATE SEQUENCE SEQ_JOB;
DROP SEQUENCE SEQ_JOB;
DELETE FROM JOB;

ALTER TABLE CHATTING_ROOM ADD CHAT_RECENT_MSG_KEY NUMBER ;
SELECT * FROM CHATTING_ROOM;
SELECT *
FROM CHATTING_GROUP cg
LEFT JOIN MEMBER m ON cg.MEMBER_KEY = m.MEMBER_KEY
LEFT JOIN CHATTING_ROOM cr ON cg.CHAT_ROOM_KEY = cr.CHAT_ROOM_KEY
LEFT JOIN CHATTING_MESSAGE cm ON cr.CHAT_RECENT_MSG_KEY = cm.CHAT_MSG_KEY
WHERE cg.CHAT_ROOM_KEY = 12
ORDER BY cm.CHAT_MSG_TIME DESC;

SELECT * FROM "MEMBER" m ;
SELECT * FROM CHATTING_ROOM cr ;
SELECT * FROM CHATTING_MESSAGE cm ;
SELECT * FROM CHATTING_GROUP cg ;

SELECT *
			FROM CHATTING_GROUP cg
			LEFT JOIN MEMBER m ON cg.MEMBER_KEY = m.MEMBER_KEY;
			LEFT JOIN CHATTING_ROOM cr ON cg.CHAT_ROOM_KEY = cr.CHAT_ROOM_KEY
			LEFT JOIN CHATTING_MESSAGE cm ON cr.CHAT_RECENT_MSG_KEY = cm.CHAT_MSG_KEY
			WHERE cg.CHAT_ROOM_KEY = 11
			ORDER BY cm.CHAT_MSG_TIME DESC;
		SELECT * FROM CHATTING_GROUP cg ;
		SELECT * FROM CHATTING_MESSAGE cm ;
		SELECT * FROM CHATTING_ROOM cm ;
		
	SELECT *, MAX(CHAT_MSG_TIME) CHAT_MSG_TIME
	FROM CHATTING_ROOM cr 
	LEFT JOIN CHATTING_MESSAGE USING (chat_room_key) 
	WHERE MEMBER_key = 1
	GROUP BY CHAT_ROOM_KEY ;
	
	SELECT * 
	FROM CHATTING_ROOM cr
	LEFT JOIN CHATTING_GROUP cg 
	ON cr.CHAT_ROOM_key = cg.CHAT_ROOM_key
	LEFT JOIN CHATTING_MESSAGE cm on cr.CHAT_RECENT_MSG_KEY = cm.CHAT_MSG_KEY 
	WHERE cg.MEMBER_key = 1
	ORDER BY chat_msg_time desc;


	SELECT * FROM CHATTING_ROOM cr ;
		
		
		SELECT cr.CHAT_ROOM_KEY FROM CHATTING_GROUP crg 
		LEFT JOIN CHATTING_ROOM cr ON crg.CHAT_ROOM_KEY=cr.CHAT_ROOM_KEY 
		LEFT JOIN CHATTING_MESSAGE cm ON CHAT_RECENT_MSG_KEY = CHAT_MSG_KEY 
		WHERE crg.MEMBER_KEY = 1
		ORDER BY chat_msg_time desc;
		
	
	
	SELECT * FROM 