-- 추가 더미 데이터 삽입
SELECT * FROM AB_EXTERNAL;
INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    7, 121, '홍길동', '010-7890-1234', 'gildong.hong@example.com', 'M', '연구개발부', '수석 연구원', '새로운 프로젝트 리더', 'N', 'RST 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    8, 3, '김유신', '010-8901-2345', 'yushin.kim@example.com', 'M', '법무부', '변호사', '우수한 법적 자문 능력 보유', 'Y', 'UVW 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    9, 123, '신사임당', '010-9012-3456', 'saimdang.shin@example.com', 'F', '교육부', '강사', '우수한 교육 능력 보유', 'N', 'XYZ 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    10, 3, '이순신', '010-0123-4567', 'soonsin.lee@example.com', 'M', '전략기획부', '전략 기획자', '회사 발전에 기여', 'Y', 'ABC 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    11, 11, '유관순', '010-1234-5678', 'kwansun.yoo@example.com', 'F', '홍보부', '홍보 담당자', '효과적인 홍보 전략 수립', 'N', 'EFG 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    11, 121, '강감찬', '010-2345-6789', 'gamchan.kang@example.com', 'M', '기술지원부', '기술지원 엔지니어', '고객 지원 우수', 'Y', 'HIJ 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    12, 121, '장영실', '010-3456-7890', 'youngsil.jang@example.com', 'M', '연구개발부', '연구원', '혁신적인 아이디어 제안', 'N', 'LMN 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    13, 121, '황진이', '010-4567-8901', 'jinlee.hwang@example.com', 'F', '디자인부', '디자이너', '창의적인 디자인 제공', 'N', 'OPQ 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    14, 121, '정약용', '010-5678-9012', 'yakyoung.jung@example.com', 'M', '연구개발부', '연구 소장', '연구 프로젝트 관리', 'Y', 'RST 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    15, 121, '이도', '010-6789-0123', 'do.lee@example.com', 'M', '전략기획부', '전략기획부장', '장기적 전략 수립', 'N', 'UVW 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    17, 17, '김유정', '010-7890-1234', 'yujung.kim@example.com', 'F', '마케팅부', '마케터', '고객 분석 우수', 'N', 'XYZ 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    18, 18, '김구', '010-8901-2345', 'goo.kim@example.com', 'M', '인사부', '인사담당', '우수한 인재 발굴 능력', 'Y', 'ABC 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    19, 19, '김소월', '010-9012-3456', 'sowol.kim@example.com', 'M', '재무부', '재무담당', '재무 분석 우수', 'N', 'EFG 회사', 'N'
);

INSERT INTO AB_EXTERNAL (
    AB_EXTERNAL_KEY, MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL, AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO, AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    20, 20, '이황', '010-0123-4567', 'whang.lee@example.com', 'M', '법무부', '법무담당', '법률 자문 능력', 'N', 'HIJ 회사', 'N'
);
