SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'BOARD_COMMENT';
CREATE SEQUENCE BOARD_COMMENT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
CREATE OR REPLACE TRIGGER BOARD_COMMENT_BEFORE_INSERT
BEFORE INSERT ON BOARD_COMMENT
FOR EACH ROW
BEGIN
    IF :NEW.BOARD_COMMENT_KEY IS NULL THEN
        SELECT BOARD_COMMENT_SEQ.NEXTVAL
        INTO :NEW.BOARD_COMMENT_KEY
        FROM dual;
    END IF;
   
   INSERT INTO BOARD_COMMENT (
    BOARD_KEY, MEMBER_KEY, BOARD_COMMENT_LEVEL, BOARD_COMMENT_DETAIL, BOARD_COMMENT_DATE, BOARD_COMMENT_REF, BOARD_COMMENT_DELETE
) VALUES (
    :BOARD_KEY, :MEMBER_KEY, :BOARD_COMMENT_LEVEL, :BOARD_COMMENT_DETAIL, :BOARD_COMMENT_DATE, :BOARD_COMMENT_REF, :BOARD_COMMENT_DELETE
);

END;
SELECT COLUMN_NAME, NULLABLE
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'BOARD_COMMENT';

SELECT 
    cols.column_name,
    cons.constraint_type,
    cons.constraint_name
FROM 
    user_constraints cons,
    user_cons_columns cols
WHERE 
    cols.table_name = 'BOARD_COMMENT'
    AND cons.constraint_name = cols.constraint_name
ORDER BY 
    cols.position;
   
   SELECT * FROM BOARD_COMMENT;
  
  ALTER TABLE BOARD_COMMENT
MODIFY (BOARD_COMMENT_DATE DEFAULT SYSDATE);

SELECT COLUMN_NAME, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'BOARD_COMMENT'
AND COLUMN_NAME = 'BOARD_COMMENT_DATE';



SELECT * FROM MEMBER;

ALTER TABLE BOARD_COMMENT
MODIFY BOARD_COMMENT_DELETE CHAR DEFAULT 'N';
