SELECT * FROM board;
ALTER TABLE BOARD ADD (BOARD_DELETE CHAR(1) DEFAULT 'N');

SELECT * FROM MEMBER;

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (1, 1, 100, '일반 게시판에 대한 첫 번째 게시글입니다.', SYSDATE, SYSDATE, 'N');
SELECT * FROM BOARD;
SELECT COLUMN_NAME, DATA_TYPE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'BOARD' AND COLUMN_NAME = 'BOARD_DELETE';
SELECT BOARD_KEY, BOARD_TITLE FROM BOARD;

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (2, 1, 100, '게시글 제목입니다.', '일반 게시판에 대한 첫 번째 게시글입니다.', SYSDATE, SYSDATE, 'N');

-- Dummy data for BOARD table (Personal/Informal Board)



INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (3, 1, 100, '사내 동호회 모집', '사내에 새로운 동호회를 만들려고 합니다. 관심 있는 분들은 댓글로 알려 주세요. 요리, 독서, 등산 등 다양한 동호회가 될 수 있습니다.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (4, 2, 100, '홈 오피스 꾸미기 아이디어 공유', '홈 오피스를 더 편리하게 꾸미기 위한 아이디어를 공유해 주세요. 어떤 가구나 장식이 좋을까요?', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (5, 2, 405, '최근 본 좋은 책 추천', '최근에 읽은 좋은 책이 있다면 추천해 주세요. 여러분의 추천 도서가 궁금합니다!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (6, 1, 406, '생일 축하드립니다!', '이번 달 생일을 맞은 동료들을 축하하는 게시판입니다. 생일 축하 메시지를 남겨 주세요!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (7, 3, 407, '사내 스포츠 경기 결과 공유', '최근 사내 스포츠 경기의 결과를 공유합니다. 승리한 팀과 경기 하이라이트를 확인해 주세요!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (8, 3, 408, '취미 생활 공유', '여러분의 취미나 여가 시간을 어떻게 보내는지 공유해 주세요. 재미있었던 활동이나 새로운 취미를 소개해 주세요!', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (9, 1, 409, '직원 추천 맛집', '여러분이 추천하는 맛집을 공유해 주세요. 점심이나 저녁에 가기 좋은 곳을 찾고 있습니다.', SYSDATE, SYSDATE, 'N');

INSERT INTO BOARD (BOARD_KEY, BOARD_CATEGORY_KEY, MEMBER_KEY, BOARD_TITLE, BOARD_DETAIL, BOARD_ENROLL_DATE, BOARD_UPDATE_DATE, BOARD_DELETE)
VALUES (10, 2, 410, '연휴 계획 공유', '다가오는 연휴에 대한 계획을 공유해 주세요. 어디로 여행을 가거나 어떤 활동을 할 예정인지 궁금합니다.', SYSDATE, SYSDATE, 'N');


