
SELECT * FROM CHATTING_ROOM ;
SELECT * FROM CHATTING_FILE ;
SELECT * FROM CHATTING_MESSAGE cm ;
SELECT * FROM MEMBER;
SELECT *
  FROM all_sequences;
  
 
ALTER TABLE CHATTING_FILE MODIFY(CHAT_MSG_FILE_POST varchar(200)); 


SELECT * FROM MEMBER WHERE MEMBER_ID='1';

ALTER TABLE CHATTING_MESSAGE MODIFY CHAT_MSG_DETAIL VARCHAR2(1000 CHAR);


	SELECT 
			cm.CHAT_MSG_KEY,
			cm.MEMBER_KEY,
			cm.CHAT_ROOM_KEY,
			cm.CHAT_MSG_DETAIL,
			cm.CHAT_MSG_TIME,
			cm.CHAT_MSG_NOTICE,
			cm.CHAT_READ_COUNT,
			cf.CHAT_MSG_FILE_POST,
			cf.FILE_CONTENT_TYPE 
		FROM chatting_message cm 
		LEFT JOIN chatting_file cf ON cm.chat_msg_key = cf.chat_msg_key 
		WHERE chat_room_key = 29
		ORDER BY chat_msg_time DESC
		
		
		
		SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'chatting_message';
	
	SELECT constraint_name, constraint_type, search_condition
FROM user_constraints
WHERE table_name = 'CHATTING_MESSAGE' AND constraint_type = 'C';


ALTER TABLE CHATTING_MESSAGE DROP CONSTRAINT SYS_C0079576;

SELECT * FROM ALL_constraints WHERE CONSTRAINT_type = 'R';

SELECT
    ac.CONSTRAINT_NAME,
    ac.TABLE_NAME,
    acc.COLUMN_NAME,
    ac.R_CONSTRAINT_NAME,
    ac2.TABLE_NAME AS REFERENCED_TABLE_NAME,
    acc2.COLUMN_NAME AS REFERENCED_COLUMN_NAME
FROM
    ALL_CONSTRAINTS ac
    JOIN ALL_CONS_COLUMNS acc ON ac.CONSTRAINT_NAME = acc.CONSTRAINT_NAME
    AND ac.OWNER = acc.OWNER
    JOIN ALL_CONSTRAINTS ac2 ON ac.R_CONSTRAINT_NAME = ac2.CONSTRAINT_NAME
    AND ac2.OWNER = ac.OWNER
    JOIN ALL_CONS_COLUMNS acc2 ON ac2.CONSTRAINT_NAME = acc2.CONSTRAINT_NAME
    AND ac2.OWNER = acc2.OWNER
    AND acc.POSITION = acc2.POSITION
WHERE
    ac.CONSTRAINT_TYPE = 'R'
ORDER BY
    ac.CONSTRAINT_NAME,
    acc.POSITION;

ALTER TABLE CHATTING_FILE ADD CONSTRAINT SYS_C0079606;

DELETE FROM CHATTING_FILE cf ;
DELETE FROM CHATTING_GROUP cg ;
DELETE FROM CHATTING_IS_READ cir ;
DELETE FROM CHATTING_MESSAGE cm ;
DELETE FROM CHATTING_ROOM cr ;

SELECT * FROM CHATTING_FILE cf ;

ALTER TABLE CHATTING_FILE RENAME COLUMN CHAT_KEY TO CHAT_ROOM_KEY;

SELECT
    ac.CONSTRAINT_NAME,
    ac.TABLE_NAME,
    acc.COLUMN_NAME,
    ac.R_CONSTRAINT_NAME,
    ac2.TABLE_NAME AS REFERENCED_TABLE_NAME,
    acc2.COLUMN_NAME AS REFERENCED_COLUMN_NAME
FROM
    ALL_CONSTRAINTS ac
    JOIN ALL_CONS_COLUMNS acc ON ac.CONSTRAINT_NAME = acc.CONSTRAINT_NAME
    AND ac.OWNER = acc.OWNER
    JOIN ALL_CONSTRAINTS ac2 ON ac.R_CONSTRAINT_NAME = ac2.CONSTRAINT_NAME
    AND ac2.OWNER = ac.OWNER
    JOIN ALL_CONS_COLUMNS acc2 ON ac2.CONSTRAINT_NAME = acc2.CONSTRAINT_NAME
    AND ac2.OWNER = acc2.OWNER
    AND acc.POSITION = acc2.POSITION
WHERE
    ac.CONSTRAINT_TYPE = 'R'
    AND ac.TABLE_NAME = 'CHATTING_IS_READ';

   
   ALTER TABLE CHATTING_IS_READ DROP CONSTRAINT FK_CHATTING_MSG_TO_IS_READ;
   
  ALTER TABLE CHATTING_IS_READ
ADD CONSTRAINT FK_CHATTING_MSG_TO_IS_READ FOREIGN KEY (CHAT_MSG_KEY)
REFERENCES CHATTING_MESSAGE (CHAT_MSG_KEY)
ON DELETE CASCADE;

SELECT * FROM CHATTING_GROUP cg ;
SELECT * FROM CHATTING_MESSAGE cm ;
DELETE FROM CHATTING_ROOM cr ;

ALTER TABLE CHATTING_GROUP ADD chat_group_status varchar2(50) CHECK (chat_group_status IN ('Y', 'N'));
ALTER TABLE CHATTING_GROUP DROP COLUMN chat_group_status;

UPDATE CHATTING_GROUP SET CHAT_GROUP_STATUS = 'Y';

ALTER TABLE CHATTING_GROUP ADD CHAT_GROUP_DATE DATE;

SELECT * FROM MEMBER;

	   	SELECT *
		FROM (
		    SELECT CHAT_ROOM_KEY, MIN(CREATED_AT) AS CREATED_AT
		    FROM CHATTING_GROUP
		    WHERE CHAT_ROOM_KEY IN (
		        SELECT CHAT_ROOM_KEY
		        FROM CHATTING_GROUP
		        WHERE MEMBER_KEY IN (1,2)
		        GROUP BY CHAT_ROOM_KEY
		        HAVING COUNT(DISTINCT MEMBER_KEY) = 2
		    )
		    GROUP BY CHAT_ROOM_KEY
		    HAVING COUNT(*) = 2
		    ORDER BY MIN(CREATED_AT) ASC
		)
		WHERE ROWNUM = 1;

SELECT COUNT(*) FROM CHATTING_GROUP WHERE CHAT_ROOM_KEY =87 AND CHAT_GROUP_STATUS = 'Y';

		DELETE FROM CHATTING_GROUP WHERE CHAT_ROOM_KEY = ${roomId}
		
		
		SELECT * FROM job;
	
	SELECT * FROM MEMBER;
	SELECT * FROM DEPARTMENT d ;

		select * from MEMBER m LEFT JOIN DEPARTMENT d ON d.DEPARTMENT_KEY = m.DEPARTMENT_KEY order by m.MEMBER_ID

		
		SELECT * FROM MEMBER;
		
			select * from MEMBER m LEFT JOIN DEPARTMENT d ON d.DEPARTMENT_KEY = m.DEPARTMENT_KEY order by m.MEMBER_ID;
