SELECT * FROM AB_EXTERNAL ae ;
);
CREATE SEQUENCE AB_EXTERNAL_SEQ
START WITH 51 -- 현재 최대 값보다 1 큰 값으로 시작
INCREMENT BY 1
NOCACHE
NOCYCLE;
SELECT AB_EXTERNAL_SEQ.NEXTVAL FROM dual;
SELECT COLUMN_NAME, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'AB_EXTERNAL'
  AND COLUMN_NAME = 'AB_EXTERNAL_KEY';
CREATE SEQUENCE AB_EXTERNAL_SEQ
START WITH 51 -- 현재 최대 값보다 1 큰 값으로 시작
INCREMENT BY 1
NOCACHE
NOCYCLE;
SELECT AB_EXTERNAL_SEQ.CURRVAL FROM dual;
SELECT COLUMN_NAME, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'AB_EXTERNAL'
AND COLUMN_NAME = 'AB_EXTERNAL_KEY';
INSERT INTO AB_EXTERNAL (
    MEMBER_KEY, AB_EXTERNAL_NAME, AB_EXTERNAL_TELL, AB_EXTERNAL_EMAIL,
    AB_EXTERNAL_GENDER, AB_EXTERNAL_DEPARTMENT, AB_EXTERNAL_JOB, AB_EXTERNAL_MEMO,
    AB_EXTERNAL_BOOKMARK, AB_EXTERNAL_COMPANY, AB_EXTERNAL_DELETE
) VALUES (
    4, '홍길동', '010-1234-5678', 'hong@example.com',
    'M', '개발부', '팀장', '특별한 메모',
    'N', '우리회사', 'N'
);

