
CREATE TABLE ALARM(
	ALARM_KEY NUMBER PRIMARY KEY,
    ALARM_TPYE VARCHAR2(100) NOT NULL,
    ALARM_PATH VARCHAR2(1000) NOT NULL,
    ALARM_RE_MEMBER NUMBER NOT NULL,
    ALARM_SEND_MEMBER NUMBER NOT NULL,
    ALARM_DATE DATE NOT NULL, 
    ALARM_DATE_READ VARCHAR2(10) DEFAULT 'N' NOT NULL 
    
);
SELECT * FROM MEMBER;
UPDATE ALARM SET ALARM_READ = 'Y' WHERE ALARM_RE_MEMBER='1'; 
 	INSERT INTO ALARM VALUES(SEQ_ALARM.NEXTVAL ,'TYPE' ,'PATH',1 ,1 ,SYSDATE ,'N');
SELECT * FROM alarm;
SELECT * FROM "MEMBER" m ;
SELECT * FROM POST_MESSAGE_RECEIVER pmr ;

ALTER TABLE alarm
RENAME COLUMN ALARM_DATE_READ TO ALARM_READ;

-- ALARM pk
CREATE SEQUENCE SEQ_ALARM
START WITH 1  -- 1부터 시작
INCREMENT BY 1  -- 1씩 증가
NOMINVALUE  -- 최소값 없음
NOMAXVALUE  -- 최대값 없음
NOCYCLE  -- 순환하지 않음
CACHE 20;  -- 20개를 캐시에 저장
SELECT  * FROM "MEMBER" m ;
DROP TABLE ALARM;

SELECT * FROM JOB;

SELECT * 
FROM POST_MESSAGE_RECEPTION R 
JOIN POST_MESSAGE_RECEIVER V
ON R.POST_MSG_REC_KEY=V.POST_MSG_REC_KEY 
JOIN "MEMBER" m 
ON m.MEMBER_KEY=R.POST_MSG_REC_MEMBER_KEY
JOIN JOB J
ON J.JOB_KEY =m.JOB_KEY 
WHERE MEMBER_REC_KEY=1
AND POST_MSG_REC_MEMBER_KEY != 1
AND DELETE_STATUS='N'  
ORDER BY R.POST_MSG_REC_KEY DESC;

 	SELECT *
    FROM POST_MESSAGE_RECEPTION R
    JOIN POST_MESSAGE_RECEIVER V ON R.POST_MSG_REC_KEY = V.POST_MSG_REC_KEY
    JOIN "MEMBER" m ON m.MEMBER_KEY = R.POST_MSG_REC_MEMBER_KEY
    JOIN JOB J ON J.JOB_KEY = m.JOB_KEY
    WHERE MEMBER_REC_KEY = 1
    AND POST_MSG_REC_MEMBER_KEY != 1
    AND DELETE_STATUS = 'N'
	AND POST_MSG_TITLE ='qwe'
	ORDER BY R.POST_MSG_REC_KEY DESC;
    
SELECT * 
FROM POST_MESSAGE_RECEPTION 
JOIN POST_MESSAGE_RECEIVER USING (POST_MSG_REC_KEY) 
WHERE MEMBER_REC_KEY = '1' 
  AND DELETE_STATUS = 'N' 
  AND POST_MSG_REC_MEMBER_KEY <> 1
ORDER BY POST_MSG_REC_KEY DESC;

SELECT * FROM MEMBER;

	SELECT * 
	FROM POST_MESSAGE_RECEPTION 
	JOIN POST_MESSAGE_RECEIVER 
	USING (POST_MSG_REC_KEY) 
	WHERE MEMBER_REC_KEY=1
	AND POST_MSG_REC_MEMBER_KEY = 1
	AND DELETE_STATUS='N' 
	ORDER BY POST_MSG_REC_KEY DESC;
	
SELECT * FROM POST_MESSAGE_RECEPTION pmre 
		JOIN POST_MESSAGE_RECEIVER pmr 
		ON pmre.POST_MSG_REC_KEY=pmr.POST_MSG_REC_KEY 
		JOIN MEMBER m 
		ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY 
		JOIN JOB j  
		ON m.JOB_KEY =j.JOB_KEY 
		LEFT JOIN POST_MESSAGE_FILE pmf
		ON pmre.POST_MSG_REC_KEY=pmf.POST_MSG_KEY
		WHERE POST_MSG_REC_MEMBER_KEY=2
		AND pmre.POST_MSG_REC_KEY=192
		AND DELETE_STATUS='N';