
UPDATE POST_MESSAGE
SET POST_MSG_TITLE = 'Test Title';
SELECT * FROM "MEMBER" m ;
SELECT * FROM DEPARTMENT d ;
ALTER TABLE POST_MESSAGE_RECEPTION
RENAME COLUMN MEMBER_KEY TO MEMBER_REC_KEY;
ALTER TABLE POST_MESSAGE_RECEIVER ADD (DELETE_STATUS VARCHAR2(10));
ALTER TABLE POST_MESSAGE_RECEIVER DROP COLUMN DELETE_STATUS;
SELECT * FROM DEPARTMENT d ;
SELECT * FROM JOB j ;
INSERT INTO DEPARTMENT VALUES ('D3','개발팀'); 
INSERT INTO MEMBER VALUES(4, 'D3', 'J1', 'user02', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'박진형', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(5, 'D3', 'J2', 'user03', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'이성록', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(6, 'D3', 'J4', 'user04', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'이우석', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(7, 'D3', 'J4', 'user05', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'서보민', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(8, 'D3', 'J4', 'user06', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'이기수', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(9, 'D3', 'J4', 'user07', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'김혜정', 'F','재직',SYSDATE );
	
SELECT COUNT(*) FROM POST_MESSAGE_SEND
		WHERE SEND_DELETE_STATUS='N' 
		AND SEND_MEMBER_KEY ='1';
SELECT * FROM POST_MESSAGE_SEND pms 
		JOIN POST_MESSAGE_RECEIVER pmr 
		ON pms.POST_MSG_SEND_KEY=pmr.POST_MSG_REC_KEY 
		JOIN MEMBER m 
		ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY 
		WHERE SEND_MEMBER_KEY ='1'
		AND SEND_DELETE_STATUS='N' 
		ORDER BY POST_MSG_SEND_KEY DESC;
	
		SELECT * FROM POST_MESSAGE_RECEPTION JOIN POST_MESSAGE_RECEIVER USING (POST_MSG_REC_KEY) 
		WHERE MEMBER_REC_KEY='1' AND DELETE_STATUS='N' ORDER BY POST_MSG_REC_KEY DESC;
		
SELECT * FROM POST_MESSAGE_RECEPTION;
SELECT * FROM POST_MESSAGE_RECEIVER;
SELECT * FROM POST_MESSAGE_SEND;
SELECT * FROM "MEMBER" m ;
ALTER TABLE POST_MESSAGE_RECEIVER
MODIFY COLUMN DELETE_STATUS SET DEFAULT 'N';

SELECT * FROM POST_MESSAGE_RECEIVER pmr ;
ALTER TABLE POST_MESSAGE_RECEPTION 
RENAME TO POST_MESSAGE_RECEIVER;

ALTER TABLE POST_MESSAGE_FILE
ADD ( POST_MSG_SEND_KEY NUMBER NOT NULL);

CREATE TABLE POST_MESSAGE_SEND (
    POST_MSG_SEND_KEY NUMBER PRIMARY KEY NOT NULL,
    SEND_MEMBER_KEY NUMBER NOT NULL,
    POST_MSG_SEND_TITLE VARCHAR2(255) NOT NULL,
    POST_MSG_SEND_DETAIL VARCHAR2(2000) NOT NULL,
    POST_MSG_SEND_TIME DATE NOT NULL,
    POST_MSG_SEND_RESERVATION DATE NULL,
    SEND_DELETE_STATUS VARCHAR2(10) DEFAULT 'N' NOT NULL
);
	
		SELECT * FROM POST_MESSAGE_SEND pms 
		JOIN POST_MESSAGE_RECEIVER pmr 
		ON pms.POST_MSG_SEND_KEY=pmr.POST_MSG_REC_KEY 
		JOIN MEMBER m 
		ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY 
		
		WHERE SEND_MEMBER_KEY ='1'
		AND SEND_DELETE_STATUS='N'
		ORDER BY POST_MSG_SEND_KEY DESC ; 
INSERT INTO POST_MESSAGE_SEND VALUES(1, 1, '안녕하세요', '디테일', SYSDATE, NULL,DEFAULT );

SELECT * FROM POST_MESSAGE_FILE;

ALTER TABLE POST_MESSAGE_FILE
RENAME COLUMN  POST_MSG_KEY TO  POST_MSG_REC_KEY;

ALTER TABLE POST_MESSAGE
RENAME TO POST_MESSAGE_RECEPTION;

SELECT * FROM POST_MESSAGE JOIN POST_MESSAGE_RECEPTION USING (POST_MSG_KEY);

INSERT INTO POST_MESSAGE_RECEPTION VALUES (SEQ_PMR.NEXTVAL,3,15);
INSERT INTO MEMBER VALUES(2, 1, 1, 'admin', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, SYSDATE, 010, '경기도', 1 );
SELECT * FROM MEMBER;
INSERT INTO MEMBER VALUES(3, 1, 'J4', 'user01', '1234', '0101313', 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '경기도', 1,'김김','F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(4, 'D1', 'J4', 'user01', '1234', '0101313', 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '경기도', 1,'김김','F','재직',SYSDATE );
SELECT * FROM MEMBER JOIN DEPARTMENT USING (DEPARTMENT_KEY) LEFT JOIN JOB USING(JOB_KEY) ORDER BY JOB_KEY ;
SELECT * FROM POST_MESSAGE JOIN POST_MESSAGE_RECEPTION USING (POST_MSG_KEY) WHERE MEMBER_REC_KEY='2'ORDER BY POST_MSG_KEY DESC;
select SEQ_PM.NEXTVAL from dual;
SELECT * FROM POST_MESSAGE pm ;
 alter table POST_MESSAGE_RECEPTION modify(POST_MSG_DETAIL VARCHAR2(1000));
-- NOTE pk
CREATE SEQUENCE SEQ_PM
START WITH 1  -- 1부터 시작
INCREMENT BY 1  -- 1씩 증가
NOMINVALUE  -- 최소값 없음
NOMAXVALUE  -- 최대값 없음
NOCYCLE  -- 순환하지 않음
CACHE 20;  -- 20개를 캐시에 저장

-- note receiver pk
CREATE SEQUENCE SEQ_PMR
START WITH 1  -- 1부터 시작
INCREMENT BY 1  -- 1씩 증가
NOMINVALUE  -- 최소값 없음
NOMAXVALUE  -- 최대값 없음
NOCYCLE  -- 순환하지 않음
CACHE 20;  -- 20개를 캐시에 저장

SELECT * FROM POST_MESSAGE_SEND pms JOIN POST_MESSAGE_RECEIVER pmr ON pms.POST_MSG_SEND_KEY=pmr.POST_MSG_REC_KEY JOIN MEMBER m ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY WHERE SEND_MEMBER_KEY ='1' AND SEND_DELETE_STATUS='N' ;
SELECT * FROM POST_MESSAGE_RECEPTION pmrtion JOIN POST_MESSAGE_RECEIVER pmr ON PMRTION.POST_MSG_REC_KEY=pmr.POST_MSG_REC_KEY JOIN MEMBER m ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY ;
SELECT * FROM POST_MESSAGE_send;
SELECT * FROM POST_MESSAGE_RECEPTION ;

	