
UPDATE POST_MESSAGE
SET POST_MSG_TITLE = 'Test Title';
SELECT * FROM "MEMBER" m ;
SELECT * FROM DEPARTMENT d ;
ALTER TABLE POST_MESSAGE_RECEPTION
RENAME COLUMN MEMBER_KEY TO MEMBER_REC_KEY;
ALTER TABLE POST_MESSAGE_RECEIVER ADD (DELETE_STATUS VARCHAR2(10));
ALTER TABLE POST_MESSAGE_RECEIVER DROP COLUMN DELETE_STATUS;
SELECT * FROM DEPARTMENT d ;
SELECT * FROM JOB j ;
INSERT INTO DEPARTMENT VALUES ('D3','개발팀'); 
INSERT INTO MEMBER VALUES(4, 'D3', 'J1', 'user02', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'박진형', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(5, 'D3', 'J2', 'user03', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'이성록', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(6, 'D3', 'J4', 'user04', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'이우석', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(7, 'D3', 'J4', 'user05', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'서보민', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(8, 'D3', 'J4', 'user06', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'이기수', 'F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(9, 'D3', 'J4', 'user07', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '서울', 1,'김혜정', 'F','재직',SYSDATE );
	
SELECT COUNT(*) FROM POST_MESSAGE_SEND
		WHERE SEND_DELETE_STATUS='N' 
		AND SEND_MEMBER_KEY ='1';

SELECT * FROM POST_MESSAGE_FILE PMF JOIN POST_MESSAGE_RECEPTION PMRE ON PMF.POST_MSG_KEY=PMRE.POST_MSG_REC_KEY
JOIN POST_MESSAGE_SEND pms ON PMF.POST_MSG_KEY =PMS.POST_MSG_SEND_KEY WHERE PMF.POST_MSG_KEY='193';
	
	
	
		SELECT * FROM POST_MESSAGE_RECEPTION JOIN POST_MESSAGE_RECEIVER USING (POST_MSG_REC_KEY) 
		WHERE MEMBER_REC_KEY='1' AND DELETE_STATUS='N' ORDER BY POST_MSG_REC_KEY DESC;
SELECT * FROM POST_MESSAGE_FILE;
INSERT INTO POST_MESSAGE_FILE VALUES (SEQ_noteFile.NEXTVAL ,194,'QQ','QQ',194 );
SELECT * FROM POST_MESSAGE_RECEPTION RECTION JOIN POST_MESSAGE_FILE pmf ON RECTION.POST_MSG_REC_KEY=pmf.POST_MSG_REC_KEY JOIN POST_MESSAGE_RECEIVER REC ON RECTION.POST_MSG_REC_KEY=REC.POST_MSG_REC_KEY;
SELECT * FROM POST_MESSAGE_RECEPTION;
SELECT * FROM POST_MESSAGE_SEND;
SELECT * FROM "MEMBER" m ;
SELECT * FROM POST_MESSAGE_RECEPTION pmr JOIN POST_MESSAGE_RECEIVER pmr2 ON pmr.POST_MSG_REC_KEY=pmr2.POST_MSG_REC_KEY JOIN MEMBER m ON pmr2.MEMBER_REC_KEY =m.MEMBER_KEY JOIN DEPARTMENT d ON m.DEPARTMENT_KEY=d.DEPARTMENT_KEY;
SELECT * FROM POST_MESSAGE_RECEPTION;
	
ALTER TABLE POST_MESSAGE_RECEPTION
ADD ( POST_MSG_REC_STATUS VARCHAR2(10)  DEFAULT 'N' NOT NULL);


ALTER TABLE POST_MESSAGE_RECEIVER
MODIFY COLUMN DELETE_STATUS SET DEFAULT 'N';

ALTER TABLE POST_MESSAGE_RECEPTION 
RENAME COLUMN MEMBER_KEY TO POST_MSG_REC_MEMBER_KEY;

SELECT * FROM POST_MESSAGE_RECEIVER pmr ;

ALTER TABLE POST_MESSAGE_RECEPTION 
RENAME TO POST_MESSAGE_RECEIVER;

ALTER TABLE POST_MESSAGE_FILE
ADD ( POST_MSG_SEND_KEY NUMBER NOT NULL);

CREATE TABLE POST_MESSAGE_SEND (
    POST_MSG_SEND_KEY NUMBER PRIMARY KEY NOT NULL,
    SEND_MEMBER_KEY NUMBER NOT NULL,
    POST_MSG_SEND_TITLE VARCHAR2(255) NOT NULL,
    POST_MSG_SEND_DETAIL VARCHAR2(2000) NOT NULL,
    POST_MSG_SEND_TIME DATE NOT NULL,
    POST_MSG_SEND_RESERVATION DATE NULL,
    SEND_DELETE_STATUS VARCHAR2(10) DEFAULT 'N' NOT NULL
);

CREATE TABLE ALARM(
    ALARM_TPYE VARCHAR2(100) NOT NULL,
    ALARM_PATH VARCHAR2(1000) NOT NULL,
    ALARM_RE_MEMBER NUMBER NOT NULL,
    ALARM_SEND_MEMBER NUMBER NOT NULL
    
);
	
		SELECT * FROM POST_MESSAGE_SEND pms 
		JOIN POST_MESSAGE_RECEIVER pmr 
		ON pms.POST_MSG_SEND_KEY=pmr.POST_MSG_REC_KEY 
		JOIN MEMBER m 
		ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY 
		
		WHERE SEND_MEMBER_KEY ='1'
		AND SEND_DELETE_STATUS='N'
		ORDER BY POST_MSG_SEND_KEY DESC ; 
INSERT INTO POST_MESSAGE_SEND VALUES(1, 1, '안녕하세요', '디테일', SYSDATE, NULL,DEFAULT );

SELECT * 
FROM POST_MESSAGE_FILE PMF 
JOIN POST_MESSAGE_RECEPTION PMRE 
    ON PMF.POST_MSG_KEY= PMRE.POST_MSG_REC_KEY 
JOIN POST_MESSAGE_RECEIVER PMR 
    ON PMR.POST_REC_KEY = PMF.POST_MSG_KEY
WHERE POST_MSG_KEY = 193;

SELECT * FROM POST_MESSAGE_RECEIVER pmr ;
SELECT * FROM POST_MESSAGE_SEND pms ;
ALTER TABLE POST_MESSAGE_FILE
RENAME COLUMN  POST_MSG_SEND_KEY TO  POST_MSG_SEND_FILE_KEY;

UPDATE POST_MESSAGE_RECEIVER
SET DELETE_STATUS = 'Y'
WHERE POST_MSG_REC_KEY = '1'
AND MEMBER_REC_KEY ='1';

ALTER TABLE POST_MESSAGE
RENAME TO POST_MESSAGE_RECEPTION;

SELECT * FROM POST_MESSAGE JOIN POST_MESSAGE_RECEPTION USING (POST_MSG_KEY);

INSERT INTO POST_MESSAGE_RECEPTION VALUES (SEQ_PMR.NEXTVAL,3,15);
INSERT INTO MEMBER VALUES(2, 1, 1, 'admin', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, SYSDATE, 010, '경기도', 1 );
SELECT * FROM MEMBER;
INSERT INTO MEMBER VALUES(3, 1, 'J4', 'user01', '1234', '0101313', 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '경기도', 1,'김김','F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(4, 'D1', 'J4', 'user01', '1234', '0101313', 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '경기도', 1,'김김','F','재직',SYSDATE );
SELECT * FROM MEMBER JOIN DEPARTMENT USING (DEPARTMENT_KEY) LEFT JOIN JOB USING(JOB_KEY) ORDER BY JOB_KEY ;
SELECT * FROM POST_MESSAGE JOIN POST_MESSAGE_RECEPTION USING (POST_MSG_KEY) WHERE MEMBER_REC_KEY='2'ORDER BY POST_MSG_KEY DESC;
select SEQ_PM.NEXTVAL from dual;
SELECT * FROM POST_MESSAGE_send ;
SELECT * FROM POST_MESSAGE_RECEIVER pmr ;
 alter table POST_MESSAGE_RECEPTION modify(POST_MSG_DETAIL VARCHAR2(1000));

 alter table POST_MESSAGE_FILE modify(POST_MESSAGE_FILE_POST VARCHAR2(1000));

-- NOTE pk
CREATE SEQUENCE SEQ_PM
START WITH 1  -- 1부터 시작
INCREMENT BY 1  -- 1씩 증가
NOMINVALUE  -- 최소값 없음
NOMAXVALUE  -- 최대값 없음
NOCYCLE  -- 순환하지 않음
CACHE 20;  -- 20개를 캐시에 저장

--noteFile pk
CREATE SEQUENCE SEQ_noteFile
START WITH 1  -- 1부터 시작
INCREMENT BY 1  -- 1씩 증가
NOMINVALUE  -- 최소값 없음
NOMAXVALUE  -- 최대값 없음
NOCYCLE  -- 순환하지 않음
CACHE 20;  -- 20개를 캐시에 저장

-- note receiver pk
CREATE SEQUENCE SEQ_PMR
START WITH 1  -- 1부터 시작
INCREMENT BY 1  -- 1씩 증가
NOMINVALUE  -- 최소값 없음
NOMAXVALUE  -- 최대값 없음
NOCYCLE  -- 순환하지 않음
CACHE 20;  -- 20개를 캐시에 저장

SELECT * FROM POST_MESSAGE_SEND pms 
		JOIN POST_MESSAGE_RECEIVER pmr 
		ON pms.POST_MSG_SEND_KEY=pmr.POST_MSG_REC_KEY 
		JOIN MEMBER m 
		ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY 
		JOIN JOB j  
		ON m.JOB_KEY =j.JOB_KEY 
		LEFT JOIN POST_MESSAGE_FILE pmf
		ON pms.POST_MSG_SEND_KEY=pmf.POST_MSG_SEND_KEY
		WHERE SEND_MEMBER_KEY ='1'
		AND pms.POST_MSG_SEND_KEY='182'
		AND SEND_DELETE_STATUS='N';

SELECT * FROM POST_MESSAGE_RECEPTION pmre 
		JOIN POST_MESSAGE_RECEIVER pmr 
		ON pmre.POST_MSG_REC_KEY=pmr.POST_MSG_REC_KEY 
		JOIN MEMBER m 
		ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY 
		JOIN JOB j  
		ON m.JOB_KEY =j.JOB_KEY 
		LEFT JOIN POST_MESSAGE_FILE pmf
		ON pmre.POST_MSG_REC_KEY=pmf.POST_MSG_KEY
		WHERE POST_MSG_REC_MEMBER_KEY =#{memberKey}
		AND pmre.POST_MSG_REC_KEY=#{postMsgRecKey}
		AND DELETE_STATUS='N';	
	
	SELECT * FROM POST_MESSAGE_RECEPTION pmre 
		JOIN POST_MESSAGE_RECEIVER pmr 
		ON pmre.POST_MSG_REC_KEY=pmr.POST_MSG_REC_KEY 
		JOIN MEMBER m 
		ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY 
		JOIN JOB j  
		ON m.JOB_KEY =j.JOB_KEY 
		LEFT JOIN POST_MESSAGE_FILE pmf
		ON pmre.POST_MSG_REC_KEY=pmf.POST_MSG_KEY
		WHERE POST_MSG_REC_MEMBER_KEY ='1'
		AND pmre.POST_MSG_REC_KEY='274'
		AND DELETE_STATUS='N';	
		
SELECT * FROM POST_MESSAGE_SEND pms JOIN POST_MESSAGE_RECEIVER pmr ON pms.POST_MSG_SEND_KEY=pmr.POST_MSG_REC_KEY JOIN MEMBER m ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY WHERE SEND_MEMBER_KEY ='1' AND SEND_DELETE_STATUS='N' ;
SELECT * FROM POST_MESSAGE_RECEPTION pmrtion JOIN POST_MESSAGE_RECEIVER pmr ON PMRTION.POST_MSG_REC_KEY=pmr.POST_MSG_REC_KEY JOIN MEMBER m ON pmr.MEMBER_REC_KEY=m.MEMBER_KEY ;
SELECT * FROM POST_MESSAGE_send;
SELECT * FROM POST_MESSAGE_RECEIVER ;
SELECT * FROM POST_MESSAGE_FILE pmf ;
SELECT * FROM POST_MESSAGE_SEND pms 
		JOIN POST_MESSAGE_RECEIVER pmr 
		ON pms.POST_MSG_SEND_KEY=pmr.POST_MSG_REC_KEY;
	