


SELECT * FROM DEPARTMENT d ;
ALTER TABLE POST_MESSAGE_RECEPTION
RENAME COLUMN MEMBER_KEY TO MEMBER_REC_KEY;


SELECT * FROM POST_MESSAGE;
SELECT * FROM POST_MESSAGE_RECEPTION pmr ;

SELECT * FROM POST_MESSAGE JOIN POST_MESSAGE_RECEPTION USING (POST_MSG_KEY);

INSERT INTO POST_MESSAGE_RECEPTION VALUES (SEQ_PMR.NEXTVAL,3,15);
INSERT INTO MEMBER VALUES(2, 1, 1, 'admin', 1234, 0101313, 'admin@naver.com', 'asd' , SYSDATE, SYSDATE, 010, '경기도', 1 );
SELECT * FROM MEMBER;
INSERT INTO MEMBER VALUES(3, 1, 'J4', 'user01', '1234', '0101313', 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '경기도', 1,'김김','F','재직',SYSDATE );
INSERT INTO MEMBER VALUES(4, 'D1', 'J4', 'user01', '1234', '0101313', 'admin@naver.com', 'asd' , SYSDATE, NULL, 010, '경기도', 1,'김김','F','재직',SYSDATE );
SELECT * FROM MEMBER JOIN DEPARTMENT USING (DEPARTMENT_KEY);

select SEQ_PM.NEXTVAL from dual;

-- NOTE pk
CREATE SEQUENCE SEQ_PM
START WITH 1  -- 1부터 시작
INCREMENT BY 1  -- 1씩 증가
NOMINVALUE  -- 최소값 없음
NOMAXVALUE  -- 최대값 없음
NOCYCLE  -- 순환하지 않음
CACHE 20;  -- 20개를 캐시에 저장

-- note receiver pk
CREATE SEQUENCE SEQ_PMR
START WITH 1  -- 1부터 시작
INCREMENT BY 1  -- 1씩 증가
NOMINVALUE  -- 최소값 없음
NOMAXVALUE  -- 최대값 없음
NOCYCLE  -- 순환하지 않음
CACHE 20;  -- 20개를 캐시에 저장



INSERT INTO POST_MESSAGE VALUES(SEQ_PM.NEXTVAL ,1 ,'안녕하세요' ,SYSDATE ,null);
