SELECT * FROM MEMBER;
SELECT * FROM DEPARTMENT;
SELECT * FROM ACCESS_LEVEL;
ALTER TABLE MEMBER
ADD MEMBER_NAME VARCHAR2(50);

CREATE SEQUENCE SEQ_MEMBER
START WITH 100
INCREMENT BY 1;
DROP SEQUENCE SEQ_MEMBER;

ALTER TABLE MEMBER
MODIFY MEMBER_NAME VARCHAR2(50) DEFAULT '아무개' NOT NULL;/*아직 안함*/

ALTER TABLE MEMBER
ADD MEMBER_GENDER VARCHAR2(3);

ALTER TABLE MEMBER
ADD MEMBER_STATE VARCHAR2(50);

ALTER TABLE MEMBER
ADD MEMBER_BIRTHDATE DATE;

INSERT INTO ACCESS_LEVEL VALUES(3,3);
